export const CONSTANTS = {
  SOOS: {
    API_KEY_ENV_VAR: "SOOS_API_KEY",
    CLIENT_ID_ENV_VAR: "SOOS_CLIENT_ID",
    DEFAULT_INTEGRATION_TYPE: "Script",
  },
  STATUS: {
    DELAY_TIME: 5000,
    MAX_ATTEMPTS: 10,
  },
};
